// Comprehensive food database with deterministic nutrition data per 100g
// All values are per 100g cooked weight

export interface FoodEntry {
  code: string;
  name: string;
  aliases: string[];
  cuisine: string;
  category: string;
  isVeg: boolean;
  // Nutrition per 100g
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  sodium: number; // mg
  // Default serving
  defaultServingG: number;
  defaultServingLabel: string;
  servingOptions: ServingOption[];
  // Tags
  tags: string[];
}

export interface ServingOption {
  label: string;
  grams: number;
}

export const FOOD_DATABASE: Record<string, FoodEntry> = {
  // ═══════════════════════════════════════
  // INDIAN / SOUTH INDIAN / ANDHRA / TELANGANA
  // ═══════════════════════════════════════
  IDLI: {
    code: "IDLI",
    name: "Idli",
    aliases: ["idly", "steamed idli"],
    cuisine: "South Indian",
    category: "Breakfast",
    isVeg: true,
    calories: 130, protein: 3.5, carbs: 27, fat: 0.5, fiber: 0.8, sugar: 0.5, sodium: 280,
    defaultServingG: 80,
    defaultServingLabel: "2 pieces",
    servingOptions: [
      { label: "1 piece (40g)", grams: 40 },
      { label: "2 pieces (80g)", grams: 80 },
      { label: "3 pieces (120g)", grams: 120 },
      { label: "4 pieces (160g)", grams: 160 },
    ],
    tags: ["steamed", "fermented", "light"],
  },
  DOSA_PLAIN: {
    code: "DOSA_PLAIN",
    name: "Plain Dosa",
    aliases: ["dosa", "sada dosa"],
    cuisine: "South Indian",
    category: "Breakfast",
    isVeg: true,
    calories: 168, protein: 4, carbs: 28, fat: 4.5, fiber: 1, sugar: 1, sodium: 320,
    defaultServingG: 120,
    defaultServingLabel: "1 dosa",
    servingOptions: [
      { label: "1 dosa (120g)", grams: 120 },
      { label: "2 dosas (240g)", grams: 240 },
    ],
    tags: ["fermented", "crispy"],
  },
  DOSA_MASALA: {
    code: "DOSA_MASALA",
    name: "Masala Dosa",
    aliases: ["masala dosa", "potato dosa"],
    cuisine: "South Indian",
    category: "Breakfast",
    isVeg: true,
    calories: 195, protein: 4.5, carbs: 30, fat: 6, fiber: 1.5, sugar: 1.5, sodium: 380,
    defaultServingG: 200,
    defaultServingLabel: "1 masala dosa",
    servingOptions: [
      { label: "1 dosa (200g)", grams: 200 },
      { label: "Half (100g)", grams: 100 },
    ],
    tags: ["fermented", "crispy", "stuffed"],
  },
  DOSA_GHEE: {
    code: "DOSA_GHEE",
    name: "Ghee Dosa",
    aliases: ["ghee dosa", "ghee roast dosa", "neyy dosa"],
    cuisine: "South Indian",
    category: "Breakfast",
    isVeg: true,
    calories: 230, protein: 4, carbs: 28, fat: 11, fiber: 1, sugar: 1, sodium: 340,
    defaultServingG: 130,
    defaultServingLabel: "1 dosa",
    servingOptions: [
      { label: "1 dosa (130g)", grams: 130 },
      { label: "2 dosas (260g)", grams: 260 },
    ],
    tags: ["fermented", "crispy", "ghee-rich"],
  },
  PESARATTU: {
    code: "PESARATTU",
    name: "Pesarattu",
    aliases: ["pesarattu dosa", "green gram dosa", "moong dosa"],
    cuisine: "Andhra",
    category: "Breakfast",
    isVeg: true,
    calories: 150, protein: 7, carbs: 22, fat: 3.5, fiber: 2, sugar: 1, sodium: 250,
    defaultServingG: 150,
    defaultServingLabel: "1 pesarattu",
    servingOptions: [
      { label: "1 piece (150g)", grams: 150 },
      { label: "2 pieces (300g)", grams: 300 },
    ],
    tags: ["protein-rich", "healthy"],
  },
  UPMA: {
    code: "UPMA",
    name: "Upma",
    aliases: ["uppuma", "rava upma"],
    cuisine: "South Indian",
    category: "Breakfast",
    isVeg: true,
    calories: 155, protein: 4, carbs: 24, fat: 5, fiber: 1.5, sugar: 1, sodium: 350,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["semolina"],
  },
  PONGAL: {
    code: "PONGAL",
    name: "Pongal",
    aliases: ["ven pongal", "khara pongal"],
    cuisine: "South Indian",
    category: "Breakfast",
    isVeg: true,
    calories: 175, protein: 5, carbs: 25, fat: 6, fiber: 1.5, sugar: 0.5, sodium: 300,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["rice", "dal", "ghee"],
  },
  VADA: {
    code: "VADA",
    name: "Medu Vada",
    aliases: ["vada", "medu vada", "urad vada", "garelu"],
    cuisine: "South Indian",
    category: "Breakfast",
    isVeg: true,
    calories: 290, protein: 10, carbs: 25, fat: 17, fiber: 3, sugar: 1, sodium: 400,
    defaultServingG: 50,
    defaultServingLabel: "1 vada",
    servingOptions: [
      { label: "1 vada (50g)", grams: 50 },
      { label: "2 vadas (100g)", grams: 100 },
      { label: "3 vadas (150g)", grams: 150 },
    ],
    tags: ["deep-fried", "protein-rich"],
  },
  SAMBAR: {
    code: "SAMBAR",
    name: "Sambar",
    aliases: ["sambhar", "sambar"],
    cuisine: "South Indian",
    category: "Side",
    isVeg: true,
    calories: 65, protein: 3, carbs: 9, fat: 1.5, fiber: 2, sugar: 2, sodium: 500,
    defaultServingG: 150,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (150g)", grams: 150 },
      { label: "½ bowl (75g)", grams: 75 },
      { label: "1 cup (200g)", grams: 200 },
    ],
    tags: ["dal", "vegetables", "healthy"],
  },
  RASAM: {
    code: "RASAM",
    name: "Rasam",
    aliases: ["chaaru", "saaru"],
    cuisine: "South Indian",
    category: "Side",
    isVeg: true,
    calories: 35, protein: 1.5, carbs: 5, fat: 0.8, fiber: 0.5, sugar: 1, sodium: 600,
    defaultServingG: 150,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (150g)", grams: 150 },
      { label: "1 cup (200g)", grams: 200 },
    ],
    tags: ["light", "digestive"],
  },
  CURD_RICE: {
    code: "CURD_RICE",
    name: "Curd Rice",
    aliases: ["thayir sadam", "dahi chawal", "perugu annam"],
    cuisine: "South Indian",
    category: "Rice",
    isVeg: true,
    calories: 140, protein: 4, carbs: 22, fat: 3.5, fiber: 0.5, sugar: 2, sodium: 300,
    defaultServingG: 250,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (250g)", grams: 250 },
      { label: "½ bowl (125g)", grams: 125 },
    ],
    tags: ["probiotic", "cooling"],
  },
  LEMON_RICE: {
    code: "LEMON_RICE",
    name: "Lemon Rice",
    aliases: ["nimmakaya annam", "chitranna"],
    cuisine: "South Indian",
    category: "Rice",
    isVeg: true,
    calories: 180, protein: 3, carbs: 30, fat: 5, fiber: 1, sugar: 1, sodium: 350,
    defaultServingG: 200,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (200g)", grams: 200 },
      { label: "½ plate (100g)", grams: 100 },
    ],
    tags: ["tangy", "rice"],
  },
  CHAPATI: {
    code: "CHAPATI",
    name: "Chapati",
    aliases: ["roti", "phulka", "chapathi"],
    cuisine: "Indian",
    category: "Bread",
    isVeg: true,
    calories: 240, protein: 8, carbs: 42, fat: 5, fiber: 3, sugar: 1, sodium: 350,
    defaultServingG: 45,
    defaultServingLabel: "1 chapati",
    servingOptions: [
      { label: "1 chapati (45g)", grams: 45 },
      { label: "2 chapatis (90g)", grams: 90 },
      { label: "3 chapatis (135g)", grams: 135 },
    ],
    tags: ["whole-wheat"],
  },
  POORI: {
    code: "POORI",
    name: "Poori",
    aliases: ["puri", "poori"],
    cuisine: "Indian",
    category: "Bread",
    isVeg: true,
    calories: 320, protein: 7, carbs: 40, fat: 14, fiber: 2, sugar: 1, sodium: 400,
    defaultServingG: 40,
    defaultServingLabel: "1 poori",
    servingOptions: [
      { label: "1 poori (40g)", grams: 40 },
      { label: "2 pooris (80g)", grams: 80 },
      { label: "3 pooris (120g)", grams: 120 },
    ],
    tags: ["deep-fried"],
  },
  BIRYANI_CHICKEN: {
    code: "BIRYANI_CHICKEN",
    name: "Chicken Biryani",
    aliases: ["chicken biryani", "hyderabadi biryani", "chicken dum biryani"],
    cuisine: "Indian",
    category: "Rice",
    isVeg: false,
    calories: 190, protein: 10, carbs: 22, fat: 7, fiber: 0.8, sugar: 1.5, sodium: 480,
    defaultServingG: 350,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "Full plate (350g)", grams: 350 },
      { label: "Half plate (175g)", grams: 175 },
      { label: "1 bowl (250g)", grams: 250 },
    ],
    tags: ["rice", "spiced", "layered"],
  },
  BIRYANI_MUTTON: {
    code: "BIRYANI_MUTTON",
    name: "Mutton Biryani",
    aliases: ["mutton biryani", "goat biryani", "lamb biryani"],
    cuisine: "Indian",
    category: "Rice",
    isVeg: false,
    calories: 210, protein: 11, carbs: 21, fat: 9, fiber: 0.8, sugar: 1.5, sodium: 500,
    defaultServingG: 350,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "Full plate (350g)", grams: 350 },
      { label: "Half plate (175g)", grams: 175 },
      { label: "1 bowl (250g)", grams: 250 },
    ],
    tags: ["rice", "spiced", "rich"],
  },
  BIRYANI_EGG: {
    code: "BIRYANI_EGG",
    name: "Egg Biryani",
    aliases: ["egg biryani", "anda biryani"],
    cuisine: "Indian",
    category: "Rice",
    isVeg: false,
    calories: 175, protein: 8, carbs: 23, fat: 6, fiber: 0.8, sugar: 1.5, sodium: 460,
    defaultServingG: 350,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "Full plate (350g)", grams: 350 },
      { label: "Half plate (175g)", grams: 175 },
      { label: "1 bowl (250g)", grams: 250 },
    ],
    tags: ["rice", "spiced"],
  },
  BIRYANI_VEG: {
    code: "BIRYANI_VEG",
    name: "Veg Biryani",
    aliases: ["vegetable biryani", "veg biryani", "veg pulao biryani"],
    cuisine: "Indian",
    category: "Rice",
    isVeg: true,
    calories: 160, protein: 4, carbs: 25, fat: 5, fiber: 1.5, sugar: 2, sodium: 420,
    defaultServingG: 350,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "Full plate (350g)", grams: 350 },
      { label: "Half plate (175g)", grams: 175 },
      { label: "1 bowl (250g)", grams: 250 },
    ],
    tags: ["rice", "spiced", "vegetables"],
  },
  VEG_PULAO: {
    code: "VEG_PULAO",
    name: "Veg Pulao",
    aliases: ["pulao", "pilaf", "vegetable pulao"],
    cuisine: "Indian",
    category: "Rice",
    isVeg: true,
    calories: 150, protein: 3.5, carbs: 24, fat: 4.5, fiber: 1.5, sugar: 1.5, sodium: 380,
    defaultServingG: 250,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (250g)", grams: 250 },
      { label: "½ plate (125g)", grams: 125 },
    ],
    tags: ["rice", "mild"],
  },
  CHICKEN_CURRY: {
    code: "CHICKEN_CURRY",
    name: "Chicken Curry",
    aliases: ["chicken curry", "chicken gravy", "kodi kura"],
    cuisine: "Indian",
    category: "Curry",
    isVeg: false,
    calories: 165, protein: 15, carbs: 6, fat: 9, fiber: 1, sugar: 2, sodium: 550,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["spiced", "gravy"],
  },
  MUTTON_CURRY: {
    code: "MUTTON_CURRY",
    name: "Mutton Curry",
    aliases: ["mutton curry", "goat curry", "mamsam kura"],
    cuisine: "Indian",
    category: "Curry",
    isVeg: false,
    calories: 195, protein: 16, carbs: 5, fat: 12, fiber: 1, sugar: 1.5, sodium: 580,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["spiced", "gravy", "rich"],
  },
  FISH_CURRY: {
    code: "FISH_CURRY",
    name: "Fish Curry",
    aliases: ["fish curry", "chepala pulusu", "meen kulambu"],
    cuisine: "Indian",
    category: "Curry",
    isVeg: false,
    calories: 120, protein: 14, carbs: 5, fat: 5, fiber: 0.5, sugar: 1.5, sodium: 520,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["tangy", "gravy"],
  },
  GONGURA_CHICKEN: {
    code: "GONGURA_CHICKEN",
    name: "Gongura Chicken",
    aliases: ["gongura chicken", "gongura kodi"],
    cuisine: "Telangana",
    category: "Curry",
    isVeg: false,
    calories: 155, protein: 14, carbs: 4, fat: 9, fiber: 1.5, sugar: 1, sodium: 500,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["tangy", "spiced", "regional"],
  },
  GONGURA_PACHADI: {
    code: "GONGURA_PACHADI",
    name: "Gongura Pachadi",
    aliases: ["gongura chutney", "gongura pickle"],
    cuisine: "Andhra",
    category: "Side",
    isVeg: true,
    calories: 120, protein: 2, carbs: 8, fat: 8, fiber: 2, sugar: 1, sodium: 800,
    defaultServingG: 30,
    defaultServingLabel: "1 tbsp",
    servingOptions: [
      { label: "1 tbsp (15g)", grams: 15 },
      { label: "2 tbsp (30g)", grams: 30 },
    ],
    tags: ["tangy", "spicy", "condiment"],
  },
  DAL: {
    code: "DAL",
    name: "Dal / Pappu",
    aliases: ["dal", "pappu", "toor dal", "dal fry", "lentil curry"],
    cuisine: "Indian",
    category: "Curry",
    isVeg: true,
    calories: 105, protein: 7, carbs: 14, fat: 2.5, fiber: 3, sugar: 1.5, sodium: 400,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["protein-rich", "healthy", "fiber"],
  },
  RICE_WHITE: {
    code: "RICE_WHITE",
    name: "White Rice",
    aliases: ["rice", "steamed rice", "plain rice", "annam"],
    cuisine: "Indian",
    category: "Rice",
    isVeg: true,
    calories: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, sugar: 0, sodium: 5,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
      { label: "1 plate (300g)", grams: 300 },
    ],
    tags: ["staple", "plain"],
  },
  SAMOSA: {
    code: "SAMOSA",
    name: "Samosa",
    aliases: ["samosa", "singara"],
    cuisine: "Indian",
    category: "Snack",
    isVeg: true,
    calories: 310, protein: 5, carbs: 32, fat: 18, fiber: 2, sugar: 2, sodium: 450,
    defaultServingG: 80,
    defaultServingLabel: "1 samosa",
    servingOptions: [
      { label: "1 samosa (80g)", grams: 80 },
      { label: "2 samosas (160g)", grams: 160 },
    ],
    tags: ["deep-fried", "snack", "potato"],
  },

  // ═══════════════════════════════════════
  // MALAYSIAN
  // ═══════════════════════════════════════
  NASI_LEMAK: {
    code: "NASI_LEMAK",
    name: "Nasi Lemak",
    aliases: ["nasi lemak", "coconut rice"],
    cuisine: "Malaysian",
    category: "Rice",
    isVeg: false,
    calories: 210, protein: 7, carbs: 28, fat: 8, fiber: 1.5, sugar: 2, sodium: 520,
    defaultServingG: 350,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (350g)", grams: 350 },
      { label: "Small (200g)", grams: 200 },
    ],
    tags: ["coconut", "sambal", "national-dish"],
  },
  NASI_GORENG: {
    code: "NASI_GORENG",
    name: "Nasi Goreng",
    aliases: ["nasi goreng", "fried rice malay"],
    cuisine: "Malaysian",
    category: "Rice",
    isVeg: false,
    calories: 195, protein: 8, carbs: 26, fat: 7, fiber: 1, sugar: 2, sodium: 600,
    defaultServingG: 300,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (300g)", grams: 300 },
      { label: "½ plate (150g)", grams: 150 },
    ],
    tags: ["fried", "wok"],
  },
  ROTI_CANAI: {
    code: "ROTI_CANAI",
    name: "Roti Canai",
    aliases: ["roti canai", "roti prata"],
    cuisine: "Malaysian",
    category: "Bread",
    isVeg: true,
    calories: 300, protein: 7, carbs: 38, fat: 13, fiber: 1, sugar: 2, sodium: 450,
    defaultServingG: 100,
    defaultServingLabel: "1 piece",
    servingOptions: [
      { label: "1 piece (100g)", grams: 100 },
      { label: "2 pieces (200g)", grams: 200 },
    ],
    tags: ["flatbread", "flaky"],
  },
  TEH_TARIK: {
    code: "TEH_TARIK",
    name: "Teh Tarik",
    aliases: ["teh tarik", "pulled tea"],
    cuisine: "Malaysian",
    category: "Drink",
    isVeg: true,
    calories: 80, protein: 2, carbs: 14, fat: 2, fiber: 0, sugar: 12, sodium: 40,
    defaultServingG: 240,
    defaultServingLabel: "1 cup",
    servingOptions: [
      { label: "1 cup (240ml)", grams: 240 },
      { label: "Large (360ml)", grams: 360 },
    ],
    tags: ["sweet", "tea", "condensed-milk"],
  },
  LAKSA: {
    code: "LAKSA",
    name: "Laksa",
    aliases: ["laksa", "curry laksa", "assam laksa"],
    cuisine: "Malaysian",
    category: "Noodles",
    isVeg: false,
    calories: 145, protein: 8, carbs: 16, fat: 6, fiber: 1, sugar: 2, sodium: 680,
    defaultServingG: 400,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (400g)", grams: 400 },
      { label: "Small (250g)", grams: 250 },
    ],
    tags: ["coconut", "spicy", "noodle-soup"],
  },
  SATAY: {
    code: "SATAY",
    name: "Satay",
    aliases: ["satay", "chicken satay", "sate"],
    cuisine: "Malaysian",
    category: "Snack",
    isVeg: false,
    calories: 220, protein: 18, carbs: 8, fat: 13, fiber: 0.5, sugar: 4, sodium: 500,
    defaultServingG: 100,
    defaultServingLabel: "4 sticks",
    servingOptions: [
      { label: "4 sticks (100g)", grams: 100 },
      { label: "6 sticks (150g)", grams: 150 },
      { label: "8 sticks (200g)", grams: 200 },
    ],
    tags: ["grilled", "peanut-sauce"],
  },
  CHAR_KWAY_TEOW: {
    code: "CHAR_KWAY_TEOW",
    name: "Char Kway Teow",
    aliases: ["char kway teow", "char kuey teow", "fried flat noodles"],
    cuisine: "Malaysian",
    category: "Noodles",
    isVeg: false,
    calories: 200, protein: 9, carbs: 24, fat: 8, fiber: 1, sugar: 2, sodium: 700,
    defaultServingG: 300,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (300g)", grams: 300 },
      { label: "½ plate (150g)", grams: 150 },
    ],
    tags: ["wok-fried", "smoky"],
  },
  RENDANG: {
    code: "RENDANG",
    name: "Rendang",
    aliases: ["rendang", "beef rendang", "chicken rendang"],
    cuisine: "Malaysian",
    category: "Curry",
    isVeg: false,
    calories: 235, protein: 20, carbs: 5, fat: 15, fiber: 1.5, sugar: 2, sodium: 550,
    defaultServingG: 150,
    defaultServingLabel: "1 serving",
    servingOptions: [
      { label: "1 serving (150g)", grams: 150 },
      { label: "½ serving (75g)", grams: 75 },
    ],
    tags: ["coconut", "spiced", "dry-curry"],
  },

  // ═══════════════════════════════════════
  // SINGAPOREAN
  // ═══════════════════════════════════════
  HAINANESE_CHICKEN_RICE: {
    code: "HAINANESE_CHICKEN_RICE",
    name: "Hainanese Chicken Rice",
    aliases: ["chicken rice", "hainanese chicken rice"],
    cuisine: "Singaporean",
    category: "Rice",
    isVeg: false,
    calories: 175, protein: 12, carbs: 20, fat: 6, fiber: 0.5, sugar: 1, sodium: 520,
    defaultServingG: 400,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (400g)", grams: 400 },
      { label: "Small (250g)", grams: 250 },
    ],
    tags: ["poached", "aromatic-rice"],
  },
  CHILI_CRAB: {
    code: "CHILI_CRAB",
    name: "Chili Crab",
    aliases: ["chili crab", "chilli crab"],
    cuisine: "Singaporean",
    category: "Seafood",
    isVeg: false,
    calories: 160, protein: 14, carbs: 10, fat: 8, fiber: 0.5, sugar: 4, sodium: 700,
    defaultServingG: 300,
    defaultServingLabel: "1 serving",
    servingOptions: [
      { label: "1 serving (300g)", grams: 300 },
      { label: "Half (150g)", grams: 150 },
    ],
    tags: ["spicy", "seafood", "iconic"],
  },

  // ═══════════════════════════════════════
  // CHINESE
  // ═══════════════════════════════════════
  FRIED_RICE: {
    code: "FRIED_RICE",
    name: "Fried Rice",
    aliases: ["fried rice", "chinese fried rice", "egg fried rice"],
    cuisine: "Chinese",
    category: "Rice",
    isVeg: false,
    calories: 185, protein: 6, carbs: 26, fat: 6.5, fiber: 1, sugar: 1.5, sodium: 620,
    defaultServingG: 300,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (300g)", grams: 300 },
      { label: "½ plate (150g)", grams: 150 },
    ],
    tags: ["wok", "egg"],
  },
  CHOW_MEIN: {
    code: "CHOW_MEIN",
    name: "Chow Mein",
    aliases: ["chow mein", "fried noodles", "stir fry noodles"],
    cuisine: "Chinese",
    category: "Noodles",
    isVeg: false,
    calories: 190, protein: 8, carbs: 28, fat: 5.5, fiber: 1.5, sugar: 3, sodium: 650,
    defaultServingG: 300,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (300g)", grams: 300 },
      { label: "½ plate (150g)", grams: 150 },
    ],
    tags: ["noodles", "stir-fried"],
  },
  DUMPLINGS: {
    code: "DUMPLINGS",
    name: "Dumplings",
    aliases: ["dumplings", "momos", "jiaozi", "dim sum"],
    cuisine: "Chinese",
    category: "Snack",
    isVeg: false,
    calories: 230, protein: 10, carbs: 28, fat: 9, fiber: 1, sugar: 2, sodium: 550,
    defaultServingG: 150,
    defaultServingLabel: "6 pieces",
    servingOptions: [
      { label: "4 pieces (100g)", grams: 100 },
      { label: "6 pieces (150g)", grams: 150 },
      { label: "8 pieces (200g)", grams: 200 },
    ],
    tags: ["steamed", "filled"],
  },
  SPRING_ROLLS: {
    code: "SPRING_ROLLS",
    name: "Spring Rolls",
    aliases: ["spring rolls", "egg rolls"],
    cuisine: "Chinese",
    category: "Snack",
    isVeg: true,
    calories: 280, protein: 5, carbs: 30, fat: 15, fiber: 1.5, sugar: 3, sodium: 480,
    defaultServingG: 100,
    defaultServingLabel: "2 rolls",
    servingOptions: [
      { label: "2 rolls (100g)", grams: 100 },
      { label: "4 rolls (200g)", grams: 200 },
    ],
    tags: ["deep-fried", "crispy"],
  },
  KUNG_PAO_CHICKEN: {
    code: "KUNG_PAO_CHICKEN",
    name: "Kung Pao Chicken",
    aliases: ["kung pao chicken", "gong bao chicken"],
    cuisine: "Chinese",
    category: "Curry",
    isVeg: false,
    calories: 175, protein: 16, carbs: 10, fat: 8, fiber: 1.5, sugar: 4, sodium: 700,
    defaultServingG: 250,
    defaultServingLabel: "1 serving",
    servingOptions: [
      { label: "1 serving (250g)", grams: 250 },
      { label: "Half (125g)", grams: 125 },
    ],
    tags: ["spicy", "peanuts", "stir-fried"],
  },

  // ═══════════════════════════════════════
  // WESTERN
  // ═══════════════════════════════════════
  GRILLED_CHICKEN: {
    code: "GRILLED_CHICKEN",
    name: "Grilled Chicken Breast",
    aliases: ["grilled chicken", "chicken breast", "baked chicken"],
    cuisine: "Western",
    category: "Protein",
    isVeg: false,
    calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, sodium: 74,
    defaultServingG: 200,
    defaultServingLabel: "1 breast",
    servingOptions: [
      { label: "1 breast (200g)", grams: 200 },
      { label: "Half (100g)", grams: 100 },
    ],
    tags: ["lean", "high-protein", "healthy"],
  },
  SCRAMBLED_EGGS: {
    code: "SCRAMBLED_EGGS",
    name: "Scrambled Eggs",
    aliases: ["scrambled eggs", "eggs"],
    cuisine: "Western",
    category: "Breakfast",
    isVeg: true,
    calories: 148, protein: 10, carbs: 2, fat: 11, fiber: 0, sugar: 1.5, sodium: 300,
    defaultServingG: 150,
    defaultServingLabel: "2 eggs",
    servingOptions: [
      { label: "1 egg (75g)", grams: 75 },
      { label: "2 eggs (150g)", grams: 150 },
      { label: "3 eggs (225g)", grams: 225 },
    ],
    tags: ["protein", "breakfast"],
  },
  PASTA: {
    code: "PASTA",
    name: "Pasta (with sauce)",
    aliases: ["pasta", "spaghetti", "penne", "macaroni"],
    cuisine: "Western",
    category: "Main",
    isVeg: true,
    calories: 165, protein: 6, carbs: 28, fat: 4, fiber: 2, sugar: 4, sodium: 400,
    defaultServingG: 300,
    defaultServingLabel: "1 plate",
    servingOptions: [
      { label: "1 plate (300g)", grams: 300 },
      { label: "½ plate (150g)", grams: 150 },
    ],
    tags: ["carb-heavy"],
  },
  OATMEAL: {
    code: "OATMEAL",
    name: "Oatmeal",
    aliases: ["oats", "porridge", "oatmeal"],
    cuisine: "Western",
    category: "Breakfast",
    isVeg: true,
    calories: 68, protein: 2.5, carbs: 12, fat: 1.4, fiber: 1.7, sugar: 0.5, sodium: 50,
    defaultServingG: 250,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (250g)", grams: 250 },
      { label: "½ bowl (125g)", grams: 125 },
    ],
    tags: ["fiber", "healthy", "whole-grain"],
  },
  SALAD_BOWL: {
    code: "SALAD_BOWL",
    name: "Salad Bowl",
    aliases: ["salad", "mixed salad", "garden salad", "caesar salad"],
    cuisine: "Western",
    category: "Main",
    isVeg: true,
    calories: 95, protein: 4, carbs: 8, fat: 5, fiber: 3, sugar: 3, sodium: 350,
    defaultServingG: 300,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (300g)", grams: 300 },
      { label: "Small (150g)", grams: 150 },
    ],
    tags: ["healthy", "light", "fiber"],
  },
  SANDWICH: {
    code: "SANDWICH",
    name: "Sandwich",
    aliases: ["sandwich", "sub", "club sandwich"],
    cuisine: "Western",
    category: "Main",
    isVeg: false,
    calories: 250, protein: 12, carbs: 28, fat: 10, fiber: 2, sugar: 3, sodium: 600,
    defaultServingG: 200,
    defaultServingLabel: "1 sandwich",
    servingOptions: [
      { label: "1 sandwich (200g)", grams: 200 },
      { label: "Half (100g)", grams: 100 },
    ],
    tags: ["bread", "filling"],
  },

  // ═══════════════════════════════════════
  // FAST FOOD
  // ═══════════════════════════════════════
  BURGER: {
    code: "BURGER",
    name: "Burger",
    aliases: ["burger", "hamburger", "cheeseburger", "chicken burger"],
    cuisine: "Fast Food",
    category: "Main",
    isVeg: false,
    calories: 250, protein: 14, carbs: 26, fat: 11, fiber: 1.5, sugar: 5, sodium: 550,
    defaultServingG: 200,
    defaultServingLabel: "1 burger",
    servingOptions: [
      { label: "Single (200g)", grams: 200 },
      { label: "Double (320g)", grams: 320 },
    ],
    tags: ["bun", "patty", "cheese"],
  },
  PIZZA: {
    code: "PIZZA",
    name: "Pizza",
    aliases: ["pizza", "pizza slice", "pepperoni pizza", "margherita"],
    cuisine: "Fast Food",
    category: "Main",
    isVeg: false,
    calories: 265, protein: 11, carbs: 30, fat: 11, fiber: 2, sugar: 3.5, sodium: 640,
    defaultServingG: 120,
    defaultServingLabel: "1 slice",
    servingOptions: [
      { label: "1 slice (120g)", grams: 120 },
      { label: "2 slices (240g)", grams: 240 },
      { label: "3 slices (360g)", grams: 360 },
      { label: "4 slices (480g)", grams: 480 },
    ],
    tags: ["cheese", "baked"],
  },
  FRIES: {
    code: "FRIES",
    name: "French Fries",
    aliases: ["fries", "french fries", "chips"],
    cuisine: "Fast Food",
    category: "Side",
    isVeg: true,
    calories: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, sugar: 0.3, sodium: 210,
    defaultServingG: 115,
    defaultServingLabel: "Medium",
    servingOptions: [
      { label: "Small (75g)", grams: 75 },
      { label: "Medium (115g)", grams: 115 },
      { label: "Large (155g)", grams: 155 },
    ],
    tags: ["deep-fried", "potato"],
  },
  FRIED_CHICKEN: {
    code: "FRIED_CHICKEN",
    name: "Fried Chicken",
    aliases: ["fried chicken", "kfc", "crispy chicken", "popcorn chicken"],
    cuisine: "Fast Food",
    category: "Main",
    isVeg: false,
    calories: 280, protein: 20, carbs: 12, fat: 17, fiber: 0.5, sugar: 0.5, sodium: 700,
    defaultServingG: 150,
    defaultServingLabel: "2 pieces",
    servingOptions: [
      { label: "1 piece (85g)", grams: 85 },
      { label: "2 pieces (150g)", grams: 150 },
      { label: "3 pieces (230g)", grams: 230 },
    ],
    tags: ["deep-fried", "battered"],
  },
  NUGGETS: {
    code: "NUGGETS",
    name: "Chicken Nuggets",
    aliases: ["nuggets", "chicken nuggets", "mcnuggets"],
    cuisine: "Fast Food",
    category: "Snack",
    isVeg: false,
    calories: 296, protein: 16, carbs: 18, fat: 18, fiber: 1, sugar: 0.5, sodium: 560,
    defaultServingG: 100,
    defaultServingLabel: "6 pieces",
    servingOptions: [
      { label: "4 pieces (65g)", grams: 65 },
      { label: "6 pieces (100g)", grams: 100 },
      { label: "10 pieces (165g)", grams: 165 },
    ],
    tags: ["deep-fried", "battered"],
  },
  SHAWARMA: {
    code: "SHAWARMA",
    name: "Shawarma",
    aliases: ["shawarma", "chicken shawarma", "shawarma wrap"],
    cuisine: "Fast Food",
    category: "Main",
    isVeg: false,
    calories: 230, protein: 14, carbs: 22, fat: 10, fiber: 1.5, sugar: 2, sodium: 600,
    defaultServingG: 250,
    defaultServingLabel: "1 wrap",
    servingOptions: [
      { label: "1 wrap (250g)", grams: 250 },
      { label: "Half (125g)", grams: 125 },
    ],
    tags: ["wrap", "grilled-meat"],
  },
  HOTDOG: {
    code: "HOTDOG",
    name: "Hotdog",
    aliases: ["hotdog", "hot dog", "frankfurter"],
    cuisine: "Fast Food",
    category: "Main",
    isVeg: false,
    calories: 290, protein: 10, carbs: 24, fat: 17, fiber: 1, sugar: 4, sodium: 700,
    defaultServingG: 150,
    defaultServingLabel: "1 hotdog",
    servingOptions: [
      { label: "1 hotdog (150g)", grams: 150 },
      { label: "2 hotdogs (300g)", grams: 300 },
    ],
    tags: ["processed"],
  },
  TACOS: {
    code: "TACOS",
    name: "Tacos",
    aliases: ["tacos", "taco", "chicken taco", "beef taco"],
    cuisine: "Fast Food",
    category: "Main",
    isVeg: false,
    calories: 210, protein: 10, carbs: 20, fat: 10, fiber: 2, sugar: 2, sodium: 480,
    defaultServingG: 120,
    defaultServingLabel: "1 taco",
    servingOptions: [
      { label: "1 taco (120g)", grams: 120 },
      { label: "2 tacos (240g)", grams: 240 },
      { label: "3 tacos (360g)", grams: 360 },
    ],
    tags: ["tortilla", "filling"],
  },

  // ═══════════════════════════════════════
  // SNACKS / BAKERY / DESSERTS / DRINKS
  // ═══════════════════════════════════════
  CAKE: {
    code: "CAKE",
    name: "Cake",
    aliases: ["cake", "chocolate cake", "pastry", "birthday cake"],
    cuisine: "Global",
    category: "Dessert",
    isVeg: true,
    calories: 350, protein: 4, carbs: 50, fat: 15, fiber: 1, sugar: 35, sodium: 300,
    defaultServingG: 100,
    defaultServingLabel: "1 slice",
    servingOptions: [
      { label: "1 slice (100g)", grams: 100 },
      { label: "Small (60g)", grams: 60 },
    ],
    tags: ["sweet", "bakery"],
  },
  DONUT: {
    code: "DONUT",
    name: "Donut",
    aliases: ["donut", "doughnut"],
    cuisine: "Global",
    category: "Dessert",
    isVeg: true,
    calories: 400, protein: 5, carbs: 50, fat: 20, fiber: 1, sugar: 22, sodium: 350,
    defaultServingG: 70,
    defaultServingLabel: "1 donut",
    servingOptions: [
      { label: "1 donut (70g)", grams: 70 },
      { label: "2 donuts (140g)", grams: 140 },
    ],
    tags: ["deep-fried", "sweet", "bakery"],
  },
  ICE_CREAM: {
    code: "ICE_CREAM",
    name: "Ice Cream",
    aliases: ["ice cream", "gelato", "kulfi"],
    cuisine: "Global",
    category: "Dessert",
    isVeg: true,
    calories: 207, protein: 3.5, carbs: 24, fat: 11, fiber: 0.5, sugar: 21, sodium: 80,
    defaultServingG: 100,
    defaultServingLabel: "1 scoop",
    servingOptions: [
      { label: "1 scoop (100g)", grams: 100 },
      { label: "2 scoops (200g)", grams: 200 },
    ],
    tags: ["frozen", "sweet", "creamy"],
  },
  TEA: {
    code: "TEA",
    name: "Tea (with milk & sugar)",
    aliases: ["tea", "chai", "milk tea"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 45, protein: 1.5, carbs: 7, fat: 1.5, fiber: 0, sugar: 6, sodium: 20,
    defaultServingG: 200,
    defaultServingLabel: "1 cup",
    servingOptions: [
      { label: "1 cup (200ml)", grams: 200 },
      { label: "Large (300ml)", grams: 300 },
    ],
    tags: ["hot", "caffeinated"],
  },
  COFFEE: {
    code: "COFFEE",
    name: "Coffee (with milk & sugar)",
    aliases: ["coffee", "cappuccino", "latte", "filter coffee"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 60, protein: 2, carbs: 8, fat: 2, fiber: 0, sugar: 7, sodium: 30,
    defaultServingG: 240,
    defaultServingLabel: "1 cup",
    servingOptions: [
      { label: "1 cup (240ml)", grams: 240 },
      { label: "Large (360ml)", grams: 360 },
    ],
    tags: ["hot", "caffeinated"],
  },
  COLA: {
    code: "COLA",
    name: "Cola / Soft Drink",
    aliases: ["cola", "coke", "pepsi", "soft drink", "soda"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 42, protein: 0, carbs: 10.6, fat: 0, fiber: 0, sugar: 10.6, sodium: 10,
    defaultServingG: 330,
    defaultServingLabel: "1 can",
    servingOptions: [
      { label: "1 can (330ml)", grams: 330 },
      { label: "1 glass (250ml)", grams: 250 },
      { label: "Large (500ml)", grams: 500 },
    ],
    tags: ["carbonated", "sweet"],
  },
  MILKSHAKE: {
    code: "MILKSHAKE",
    name: "Milkshake",
    aliases: ["milkshake", "shake"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 112, protein: 3.5, carbs: 18, fat: 3, fiber: 0, sugar: 16, sodium: 100,
    defaultServingG: 300,
    defaultServingLabel: "1 glass",
    servingOptions: [
      { label: "1 glass (300ml)", grams: 300 },
      { label: "Large (450ml)", grams: 450 },
    ],
    tags: ["sweet", "cold", "creamy"],
  },
  JUICE: {
    code: "JUICE",
    name: "Fruit Juice",
    aliases: ["juice", "orange juice", "mango juice", "apple juice"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 45, protein: 0.5, carbs: 10, fat: 0.2, fiber: 0.2, sugar: 9, sodium: 5,
    defaultServingG: 250,
    defaultServingLabel: "1 glass",
    servingOptions: [
      { label: "1 glass (250ml)", grams: 250 },
      { label: "Small (150ml)", grams: 150 },
    ],
    tags: ["fresh", "sweet"],
  },

  // ═══════════════════════════════════════
  // ADDITIONAL ITEMS FOR MVP
  // ═══════════════════════════════════════
  CURD: {
    code: "CURD",
    name: "Curd / Yogurt",
    aliases: ["curd", "yogurt", "dahi", "perugu", "thayir"],
    cuisine: "Indian",
    category: "Side",
    isVeg: true,
    calories: 60, protein: 3.5, carbs: 5, fat: 3.3, fiber: 0, sugar: 5, sodium: 45,
    defaultServingG: 150,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (150g)", grams: 150 },
      { label: "½ bowl (75g)", grams: 75 },
      { label: "1 cup (200g)", grams: 200 },
    ],
    tags: ["probiotic", "cooling", "healthy"],
  },
  VEG_CURRY: {
    code: "VEG_CURRY",
    name: "Veg Curry",
    aliases: ["veg curry", "vegetable curry", "mixed veg curry", "sabzi", "kura", "kootu"],
    cuisine: "Indian",
    category: "Curry",
    isVeg: true,
    calories: 95, protein: 3, carbs: 10, fat: 4.5, fiber: 2.5, sugar: 3, sodium: 450,
    defaultServingG: 200,
    defaultServingLabel: "1 bowl",
    servingOptions: [
      { label: "1 bowl (200g)", grams: 200 },
      { label: "½ bowl (100g)", grams: 100 },
    ],
    tags: ["vegetables", "gravy", "healthy"],
  },
  FRY_CURRY: {
    code: "FRY_CURRY",
    name: "Fry Curry / Dry Curry",
    aliases: ["fry curry", "dry curry", "stir fry", "vepudu", "poriyal", "fry"],
    cuisine: "Indian",
    category: "Curry",
    isVeg: true,
    calories: 130, protein: 3, carbs: 12, fat: 7, fiber: 2, sugar: 2, sodium: 400,
    defaultServingG: 150,
    defaultServingLabel: "1 serving",
    servingOptions: [
      { label: "1 serving (150g)", grams: 150 },
      { label: "½ serving (75g)", grams: 75 },
    ],
    tags: ["dry", "stir-fried", "side"],
  },
  CHUTNEY: {
    code: "CHUTNEY",
    name: "Chutney",
    aliases: ["chutney", "coconut chutney", "pachadi", "tomato chutney", "mint chutney"],
    cuisine: "South Indian",
    category: "Side",
    isVeg: true,
    calories: 80, protein: 2, carbs: 6, fat: 5, fiber: 1.5, sugar: 2, sodium: 350,
    defaultServingG: 40,
    defaultServingLabel: "2 tbsp",
    servingOptions: [
      { label: "1 tbsp (20g)", grams: 20 },
      { label: "2 tbsp (40g)", grams: 40 },
      { label: "3 tbsp (60g)", grams: 60 },
    ],
    tags: ["condiment", "coconut"],
  },
  BLACK_TEA: {
    code: "BLACK_TEA",
    name: "Black Tea",
    aliases: ["black tea", "plain tea", "tea without milk", "green tea"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 2, protein: 0, carbs: 0.5, fat: 0, fiber: 0, sugar: 0, sodium: 5,
    defaultServingG: 200,
    defaultServingLabel: "1 cup",
    servingOptions: [
      { label: "1 cup (200ml)", grams: 200 },
      { label: "Large (300ml)", grams: 300 },
    ],
    tags: ["zero-calorie", "caffeinated", "antioxidants"],
  },
  MILK_COFFEE: {
    code: "MILK_COFFEE",
    name: "Milk Coffee",
    aliases: ["milk coffee", "white coffee", "coffee with milk"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 55, protein: 2, carbs: 7, fat: 2, fiber: 0, sugar: 6, sodium: 30,
    defaultServingG: 240,
    defaultServingLabel: "1 cup",
    servingOptions: [
      { label: "1 cup (240ml)", grams: 240 },
      { label: "Large (360ml)", grams: 360 },
    ],
    tags: ["hot", "caffeinated", "milky"],
  },
  FILTER_COFFEE: {
    code: "FILTER_COFFEE",
    name: "Filter Coffee",
    aliases: ["filter coffee", "south indian coffee", "degree coffee", "kaapi"],
    cuisine: "South Indian",
    category: "Drink",
    isVeg: true,
    calories: 75, protein: 2, carbs: 9, fat: 3, fiber: 0, sugar: 8, sodium: 25,
    defaultServingG: 180,
    defaultServingLabel: "1 tumbler",
    servingOptions: [
      { label: "1 tumbler (180ml)", grams: 180 },
      { label: "Large (250ml)", grams: 250 },
    ],
    tags: ["hot", "caffeinated", "frothy", "traditional"],
  },
  BUBBLE_TEA: {
    code: "BUBBLE_TEA",
    name: "Bubble Tea",
    aliases: ["bubble tea", "boba", "boba tea", "pearl milk tea"],
    cuisine: "Global",
    category: "Drink",
    isVeg: true,
    calories: 120, protein: 1, carbs: 28, fat: 1.5, fiber: 0, sugar: 24, sodium: 30,
    defaultServingG: 400,
    defaultServingLabel: "1 cup",
    servingOptions: [
      { label: "Regular (400ml)", grams: 400 },
      { label: "Large (500ml)", grams: 500 },
      { label: "Small (300ml)", grams: 300 },
    ],
    tags: ["sweet", "cold", "tapioca"],
  },
  BUTTERMILK: {
    code: "BUTTERMILK",
    name: "Buttermilk",
    aliases: ["buttermilk", "chaas", "majjiga", "neer majjige", "mor"],
    cuisine: "Indian",
    category: "Drink",
    isVeg: true,
    calories: 22, protein: 1.5, carbs: 2.5, fat: 0.8, fiber: 0, sugar: 2, sodium: 150,
    defaultServingG: 250,
    defaultServingLabel: "1 glass",
    servingOptions: [
      { label: "1 glass (250ml)", grams: 250 },
      { label: "Large (350ml)", grams: 350 },
    ],
    tags: ["probiotic", "cooling", "digestive", "low-calorie"],
  },
  LASSI: {
    code: "LASSI",
    name: "Lassi",
    aliases: ["lassi", "sweet lassi", "mango lassi", "salt lassi"],
    cuisine: "Indian",
    category: "Drink",
    isVeg: true,
    calories: 85, protein: 3, carbs: 14, fat: 2, fiber: 0, sugar: 12, sodium: 60,
    defaultServingG: 250,
    defaultServingLabel: "1 glass",
    servingOptions: [
      { label: "1 glass (250ml)", grams: 250 },
      { label: "Large (350ml)", grams: 350 },
    ],
    tags: ["probiotic", "sweet", "cold"],
  },
  ALMONDS: {
    code: "ALMONDS",
    name: "Almonds",
    aliases: ["almonds", "badam", "almond", "soaked almonds"],
    cuisine: "Global",
    category: "Snack",
    isVeg: true,
    calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12, sugar: 4, sodium: 1,
    defaultServingG: 28,
    defaultServingLabel: "10 almonds",
    servingOptions: [
      { label: "5 almonds (14g)", grams: 14 },
      { label: "8 almonds (22g)", grams: 22 },
      { label: "10 almonds (28g)", grams: 28 },
      { label: "15 almonds (42g)", grams: 42 },
    ],
    tags: ["nuts", "protein-rich", "healthy-fat", "snack"],
  },
  SUNFLOWER_SEEDS: {
    code: "SUNFLOWER_SEEDS",
    name: "Sunflower Seeds",
    aliases: ["sunflower seeds", "sunflower", "seeds"],
    cuisine: "Global",
    category: "Snack",
    isVeg: true,
    calories: 584, protein: 21, carbs: 20, fat: 51, fiber: 9, sugar: 3, sodium: 9,
    defaultServingG: 15,
    defaultServingLabel: "10 seeds",
    servingOptions: [
      { label: "10 seeds (15g)", grams: 15 },
      { label: "1 tbsp (10g)", grams: 10 },
      { label: "2 tbsp (20g)", grams: 20 },
      { label: "¼ cup (35g)", grams: 35 },
    ],
    tags: ["seeds", "healthy-fat", "snack"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: MORE SOUTH INDIAN
  // ═══════════════════════════════════════
  MEDU_VADA: {
    code: "MEDU_VADA", name: "Medu Vada", aliases: ["medu vada", "vadai", "ulundu vada"],
    cuisine: "South Indian", category: "Breakfast", isVeg: true,
    calories: 290, protein: 9, carbs: 25, fat: 18, fiber: 2, sugar: 1, sodium: 350,
    defaultServingG: 60, defaultServingLabel: "2 vadas",
    servingOptions: [{ label: "1 vada (30g)", grams: 30 }, { label: "2 vadas (60g)", grams: 60 }, { label: "3 vadas (90g)", grams: 90 }],
    tags: ["fried", "fermented"],
  },
  RAVA_DOSA: {
    code: "RAVA_DOSA", name: "Rava Dosa", aliases: ["rava dosa", "sooji dosa", "semolina dosa"],
    cuisine: "South Indian", category: "Breakfast", isVeg: true,
    calories: 185, protein: 4, carbs: 26, fat: 7, fiber: 1, sugar: 1.5, sodium: 340,
    defaultServingG: 130, defaultServingLabel: "1 dosa",
    servingOptions: [{ label: "1 dosa (130g)", grams: 130 }, { label: "2 dosas (260g)", grams: 260 }],
    tags: ["crispy", "instant"],
  },
  UTTAPAM: {
    code: "UTTAPAM", name: "Uttapam", aliases: ["uttapam", "uthappam", "thick dosa"],
    cuisine: "South Indian", category: "Breakfast", isVeg: true,
    calories: 175, protein: 5, carbs: 28, fat: 5, fiber: 1.5, sugar: 2, sodium: 300,
    defaultServingG: 150, defaultServingLabel: "1 uttapam",
    servingOptions: [{ label: "1 uttapam (150g)", grams: 150 }, { label: "2 uttapam (300g)", grams: 300 }],
    tags: ["fermented", "soft"],
  },
  APPAM: {
    code: "APPAM", name: "Appam", aliases: ["appam", "hoppers", "palappam"],
    cuisine: "South Indian", category: "Breakfast", isVeg: true,
    calories: 120, protein: 2.5, carbs: 22, fat: 2, fiber: 0.5, sugar: 1, sodium: 200,
    defaultServingG: 70, defaultServingLabel: "1 appam",
    servingOptions: [{ label: "1 appam (70g)", grams: 70 }, { label: "2 appam (140g)", grams: 140 }, { label: "3 appam (210g)", grams: 210 }],
    tags: ["fermented", "light"],
  },
  PUTTU: {
    code: "PUTTU", name: "Puttu", aliases: ["puttu", "pittu"],
    cuisine: "South Indian", category: "Breakfast", isVeg: true,
    calories: 210, protein: 4, carbs: 38, fat: 5, fiber: 2, sugar: 1, sodium: 150,
    defaultServingG: 150, defaultServingLabel: "1 cylinder",
    servingOptions: [{ label: "1 cylinder (150g)", grams: 150 }, { label: "2 cylinders (300g)", grams: 300 }],
    tags: ["steamed", "kerala"],
  },
  IDIYAPPAM: {
    code: "IDIYAPPAM", name: "Idiyappam", aliases: ["idiyappam", "string hoppers", "nool puttu"],
    cuisine: "South Indian", category: "Breakfast", isVeg: true,
    calories: 110, protein: 2, carbs: 24, fat: 0.5, fiber: 0.5, sugar: 0.5, sodium: 180,
    defaultServingG: 60, defaultServingLabel: "2 pieces",
    servingOptions: [{ label: "2 pieces (60g)", grams: 60 }, { label: "4 pieces (120g)", grams: 120 }, { label: "6 pieces (180g)", grams: 180 }],
    tags: ["steamed", "light"],
  },
  KOZHUKATTAI: {
    code: "KOZHUKATTAI", name: "Kozhukattai", aliases: ["kozhukattai", "modak", "undrallu"],
    cuisine: "South Indian", category: "Snack", isVeg: true,
    calories: 180, protein: 3, carbs: 32, fat: 5, fiber: 1.5, sugar: 8, sodium: 100,
    defaultServingG: 80, defaultServingLabel: "3 pieces",
    servingOptions: [{ label: "2 pieces (55g)", grams: 55 }, { label: "3 pieces (80g)", grams: 80 }, { label: "5 pieces (130g)", grams: 130 }],
    tags: ["steamed", "sweet"],
  },
  BISI_BELE_BATH: {
    code: "BISI_BELE_BATH", name: "Bisi Bele Bath", aliases: ["bisi bele bath", "bisibelebath", "sambar rice"],
    cuisine: "South Indian", category: "Rice", isVeg: true,
    calories: 165, protein: 5, carbs: 28, fat: 4, fiber: 2, sugar: 2, sodium: 380,
    defaultServingG: 250, defaultServingLabel: "1 plate",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "1 plate (250g)", grams: 250 }],
    tags: ["spicy", "one-pot"],
  },
  TAMARIND_RICE: {
    code: "TAMARIND_RICE", name: "Tamarind Rice", aliases: ["tamarind rice", "pulihora", "puliyodharai", "puliyogare"],
    cuisine: "South Indian", category: "Rice", isVeg: true,
    calories: 175, protein: 3, carbs: 32, fat: 4, fiber: 1.5, sugar: 3, sodium: 350,
    defaultServingG: 200, defaultServingLabel: "1 serving",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "1 plate (300g)", grams: 300 }],
    tags: ["tangy", "temple-food"],
  },
  COCONUT_RICE: {
    code: "COCONUT_RICE", name: "Coconut Rice", aliases: ["coconut rice", "thengai sadam", "kobbari annam"],
    cuisine: "South Indian", category: "Rice", isVeg: true,
    calories: 190, protein: 3, carbs: 30, fat: 7, fiber: 2, sugar: 1, sodium: 280,
    defaultServingG: 200, defaultServingLabel: "1 serving",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "1 plate (300g)", grams: 300 }],
    tags: ["coconut", "festive"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: NORTH INDIAN
  // ═══════════════════════════════════════
  NAAN: {
    code: "NAAN", name: "Naan", aliases: ["naan", "nan", "tandoori naan"],
    cuisine: "North Indian", category: "Bread", isVeg: true,
    calories: 260, protein: 8, carbs: 45, fat: 5, fiber: 2, sugar: 3, sodium: 420,
    defaultServingG: 90, defaultServingLabel: "1 naan",
    servingOptions: [{ label: "1 naan (90g)", grams: 90 }, { label: "2 naan (180g)", grams: 180 }],
    tags: ["tandoor", "bread"],
  },
  PARATHA: {
    code: "PARATHA", name: "Paratha", aliases: ["paratha", "parantha", "laccha paratha", "lachha paratha"],
    cuisine: "North Indian", category: "Bread", isVeg: true,
    calories: 280, protein: 6, carbs: 35, fat: 13, fiber: 2, sugar: 1, sodium: 380,
    defaultServingG: 80, defaultServingLabel: "1 paratha",
    servingOptions: [{ label: "1 paratha (80g)", grams: 80 }, { label: "2 paratha (160g)", grams: 160 }, { label: "3 paratha (240g)", grams: 240 }],
    tags: ["flaky", "layered"],
  },
  ALOO_PARATHA: {
    code: "ALOO_PARATHA", name: "Aloo Paratha", aliases: ["aloo paratha", "potato paratha", "aloo ka paratha"],
    cuisine: "North Indian", category: "Bread", isVeg: true,
    calories: 300, protein: 7, carbs: 40, fat: 13, fiber: 3, sugar: 2, sodium: 400,
    defaultServingG: 120, defaultServingLabel: "1 aloo paratha",
    servingOptions: [{ label: "1 paratha (120g)", grams: 120 }, { label: "2 paratha (240g)", grams: 240 }],
    tags: ["stuffed", "breakfast"],
  },
  PANEER_BUTTER_MASALA: {
    code: "PANEER_BUTTER_MASALA", name: "Paneer Butter Masala", aliases: ["paneer butter masala", "paneer makhani", "butter paneer"],
    cuisine: "North Indian", category: "Curry", isVeg: true,
    calories: 240, protein: 12, carbs: 10, fat: 18, fiber: 1.5, sugar: 4, sodium: 550,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["creamy", "rich", "restaurant-style"],
  },
  PALAK_PANEER: {
    code: "PALAK_PANEER", name: "Palak Paneer", aliases: ["palak paneer", "spinach paneer", "saag paneer"],
    cuisine: "North Indian", category: "Curry", isVeg: true,
    calories: 170, protein: 10, carbs: 8, fat: 12, fiber: 2.5, sugar: 2, sodium: 450,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["spinach", "healthy", "protein-rich"],
  },
  CHOLE: {
    code: "CHOLE", name: "Chole", aliases: ["chole", "chana masala", "chickpea curry", "chole masala", "chhole"],
    cuisine: "North Indian", category: "Curry", isVeg: true,
    calories: 150, protein: 8, carbs: 22, fat: 4, fiber: 6, sugar: 3, sodium: 420,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["protein-rich", "fiber-rich"],
  },
  RAJMA: {
    code: "RAJMA", name: "Rajma", aliases: ["rajma", "kidney bean curry", "rajma masala", "rajma chawal"],
    cuisine: "North Indian", category: "Curry", isVeg: true,
    calories: 140, protein: 8, carbs: 22, fat: 3.5, fiber: 6, sugar: 2, sodium: 400,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["protein-rich", "fiber-rich", "comfort-food"],
  },
  DAL_TADKA: {
    code: "DAL_TADKA", name: "Dal Tadka", aliases: ["dal tadka", "tadka dal", "dal fry", "toor dal tadka"],
    cuisine: "North Indian", category: "Curry", isVeg: true,
    calories: 120, protein: 7, carbs: 16, fat: 3.5, fiber: 3, sugar: 2, sodium: 380,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["comfort-food", "protein-rich"],
  },
  DAL_MAKHANI: {
    code: "DAL_MAKHANI", name: "Dal Makhani", aliases: ["dal makhani", "maa ki dal", "black dal"],
    cuisine: "North Indian", category: "Curry", isVeg: true,
    calories: 175, protein: 7, carbs: 18, fat: 9, fiber: 4, sugar: 2, sodium: 450,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["creamy", "rich", "slow-cooked"],
  },
  BUTTER_CHICKEN: {
    code: "BUTTER_CHICKEN", name: "Butter Chicken", aliases: ["butter chicken", "murgh makhani", "chicken makhani"],
    cuisine: "North Indian", category: "Curry", isVeg: false,
    calories: 195, protein: 15, carbs: 8, fat: 12, fiber: 1, sugar: 3, sodium: 520,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["creamy", "rich", "restaurant-style"],
  },
  TANDOORI_CHICKEN: {
    code: "TANDOORI_CHICKEN", name: "Tandoori Chicken", aliases: ["tandoori chicken", "tandoori murgh"],
    cuisine: "North Indian", category: "Non-Veg", isVeg: false,
    calories: 165, protein: 25, carbs: 3, fat: 6, fiber: 0.5, sugar: 1, sodium: 480,
    defaultServingG: 200, defaultServingLabel: "2 pieces",
    servingOptions: [{ label: "1 piece (100g)", grams: 100 }, { label: "2 pieces (200g)", grams: 200 }, { label: "quarter (250g)", grams: 250 }],
    tags: ["grilled", "high-protein", "low-carb"],
  },
  CHICKEN_TIKKA: {
    code: "CHICKEN_TIKKA", name: "Chicken Tikka", aliases: ["chicken tikka", "tikka"],
    cuisine: "North Indian", category: "Non-Veg", isVeg: false,
    calories: 175, protein: 22, carbs: 5, fat: 8, fiber: 0.5, sugar: 1, sodium: 500,
    defaultServingG: 150, defaultServingLabel: "6 pieces",
    servingOptions: [{ label: "3 pieces (75g)", grams: 75 }, { label: "6 pieces (150g)", grams: 150 }, { label: "9 pieces (225g)", grams: 225 }],
    tags: ["grilled", "high-protein"],
  },
  BIRYANI_PRAWN: {
    code: "BIRYANI_PRAWN", name: "Prawn Biryani", aliases: ["prawn biryani", "shrimp biryani", "jheenga biryani"],
    cuisine: "Hyderabadi", category: "Rice", isVeg: false,
    calories: 185, protein: 12, carbs: 28, fat: 4, fiber: 1, sugar: 1, sodium: 480,
    defaultServingG: 300, defaultServingLabel: "1 plate",
    servingOptions: [{ label: "half plate (150g)", grams: 150 }, { label: "1 plate (300g)", grams: 300 }],
    tags: ["spicy", "seafood", "festive"],
  },
  KEEMA: {
    code: "KEEMA", name: "Keema", aliases: ["keema", "kheema", "minced meat curry", "mutton keema"],
    cuisine: "North Indian", category: "Non-Veg", isVeg: false,
    calories: 200, protein: 16, carbs: 6, fat: 13, fiber: 1, sugar: 2, sodium: 450,
    defaultServingG: 180, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (180g)", grams: 180 }, { label: "half bowl (90g)", grams: 90 }],
    tags: ["spicy", "minced"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: INDIAN SNACKS & STREET FOOD
  // ═══════════════════════════════════════
  SAMOSA: {
    code: "SAMOSA", name: "Samosa", aliases: ["samosa", "samosas", "aloo samosa"],
    cuisine: "North Indian", category: "Snack", isVeg: true,
    calories: 260, protein: 5, carbs: 28, fat: 14, fiber: 2, sugar: 2, sodium: 350,
    defaultServingG: 80, defaultServingLabel: "1 samosa",
    servingOptions: [{ label: "1 samosa (80g)", grams: 80 }, { label: "2 samosas (160g)", grams: 160 }],
    tags: ["fried", "street-food"],
  },
  PAKORA: {
    code: "PAKORA", name: "Pakora", aliases: ["pakora", "pakoda", "bhajji", "bajji", "bhajiya", "onion pakora"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 300, protein: 6, carbs: 30, fat: 17, fiber: 2, sugar: 2, sodium: 400,
    defaultServingG: 60, defaultServingLabel: "4 pieces",
    servingOptions: [{ label: "3 pieces (45g)", grams: 45 }, { label: "4 pieces (60g)", grams: 60 }, { label: "6 pieces (90g)", grams: 90 }],
    tags: ["fried", "street-food", "rainy-day"],
  },
  PANI_PURI: {
    code: "PANI_PURI", name: "Pani Puri", aliases: ["pani puri", "golgappa", "gol gappa", "puchka", "pani poori"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 180, protein: 3, carbs: 30, fat: 5, fiber: 2, sugar: 3, sodium: 500,
    defaultServingG: 120, defaultServingLabel: "6 puris",
    servingOptions: [{ label: "4 puris (80g)", grams: 80 }, { label: "6 puris (120g)", grams: 120 }, { label: "8 puris (160g)", grams: 160 }],
    tags: ["street-food", "tangy", "spicy"],
  },
  BHEL_PURI: {
    code: "BHEL_PURI", name: "Bhel Puri", aliases: ["bhel puri", "bhel", "bhelpuri"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 160, protein: 4, carbs: 26, fat: 5, fiber: 2, sugar: 4, sodium: 380,
    defaultServingG: 150, defaultServingLabel: "1 plate",
    servingOptions: [{ label: "1 plate (150g)", grams: 150 }, { label: "half plate (75g)", grams: 75 }],
    tags: ["street-food", "tangy", "light"],
  },
  SEV_PURI: {
    code: "SEV_PURI", name: "Sev Puri", aliases: ["sev puri", "sevpuri"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 195, protein: 3.5, carbs: 25, fat: 9, fiber: 1.5, sugar: 3, sodium: 420,
    defaultServingG: 120, defaultServingLabel: "6 pieces",
    servingOptions: [{ label: "4 pieces (80g)", grams: 80 }, { label: "6 pieces (120g)", grams: 120 }],
    tags: ["street-food", "crispy"],
  },
  DAHI_PURI: {
    code: "DAHI_PURI", name: "Dahi Puri", aliases: ["dahi puri", "curd puri"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 170, protein: 4, carbs: 24, fat: 6, fiber: 1.5, sugar: 5, sodium: 350,
    defaultServingG: 120, defaultServingLabel: "6 pieces",
    servingOptions: [{ label: "4 pieces (80g)", grams: 80 }, { label: "6 pieces (120g)", grams: 120 }],
    tags: ["street-food", "sweet-tangy"],
  },
  PAV_BHAJI: {
    code: "PAV_BHAJI", name: "Pav Bhaji", aliases: ["pav bhaji", "pav bhajji"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 240, protein: 6, carbs: 32, fat: 10, fiber: 3, sugar: 4, sodium: 500,
    defaultServingG: 250, defaultServingLabel: "1 plate",
    servingOptions: [{ label: "1 plate (250g)", grams: 250 }, { label: "half plate (125g)", grams: 125 }],
    tags: ["street-food", "buttery"],
  },
  VADA_PAV: {
    code: "VADA_PAV", name: "Vada Pav", aliases: ["vada pav", "wada pav", "vadapav"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 280, protein: 5, carbs: 35, fat: 12, fiber: 2, sugar: 3, sodium: 450,
    defaultServingG: 120, defaultServingLabel: "1 vada pav",
    servingOptions: [{ label: "1 vada pav (120g)", grams: 120 }, { label: "2 vada pav (240g)", grams: 240 }],
    tags: ["street-food", "fried", "mumbai"],
  },
  KACHORI: {
    code: "KACHORI", name: "Kachori", aliases: ["kachori", "pyaaz kachori", "dal kachori"],
    cuisine: "North Indian", category: "Snack", isVeg: true,
    calories: 310, protein: 6, carbs: 32, fat: 18, fiber: 2, sugar: 2, sodium: 380,
    defaultServingG: 70, defaultServingLabel: "1 kachori",
    servingOptions: [{ label: "1 kachori (70g)", grams: 70 }, { label: "2 kachori (140g)", grams: 140 }],
    tags: ["fried", "street-food"],
  },
  ALOO_TIKKI: {
    code: "ALOO_TIKKI", name: "Aloo Tikki", aliases: ["aloo tikki", "potato tikki", "tikki"],
    cuisine: "North Indian", category: "Snack", isVeg: true,
    calories: 220, protein: 4, carbs: 28, fat: 10, fiber: 2, sugar: 2, sodium: 380,
    defaultServingG: 80, defaultServingLabel: "2 tikkis",
    servingOptions: [{ label: "1 tikki (40g)", grams: 40 }, { label: "2 tikkis (80g)", grams: 80 }],
    tags: ["fried", "street-food"],
  },
  DABELI: {
    code: "DABELI", name: "Dabeli", aliases: ["dabeli", "kutchi dabeli"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 230, protein: 5, carbs: 34, fat: 8, fiber: 2, sugar: 5, sodium: 420,
    defaultServingG: 130, defaultServingLabel: "1 dabeli",
    servingOptions: [{ label: "1 dabeli (130g)", grams: 130 }, { label: "2 dabeli (260g)", grams: 260 }],
    tags: ["street-food", "sweet-spicy", "gujarati"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: INDIAN SWEETS & DESSERTS
  // ═══════════════════════════════════════
  GULAB_JAMUN: {
    code: "GULAB_JAMUN", name: "Gulab Jamun", aliases: ["gulab jamun", "gulab jamoon"],
    cuisine: "Indian", category: "Dessert", isVeg: true,
    calories: 325, protein: 4, carbs: 48, fat: 13, fiber: 0.5, sugar: 38, sodium: 120,
    defaultServingG: 80, defaultServingLabel: "2 pieces",
    servingOptions: [{ label: "1 piece (40g)", grams: 40 }, { label: "2 pieces (80g)", grams: 80 }, { label: "3 pieces (120g)", grams: 120 }],
    tags: ["sweet", "fried", "festive"],
  },
  RASGULLA: {
    code: "RASGULLA", name: "Rasgulla", aliases: ["rasgulla", "rasagola", "rosogolla"],
    cuisine: "Indian", category: "Dessert", isVeg: true,
    calories: 185, protein: 4, carbs: 38, fat: 2, fiber: 0, sugar: 32, sodium: 80,
    defaultServingG: 80, defaultServingLabel: "2 pieces",
    servingOptions: [{ label: "1 piece (40g)", grams: 40 }, { label: "2 pieces (80g)", grams: 80 }, { label: "3 pieces (120g)", grams: 120 }],
    tags: ["sweet", "bengali", "festive"],
  },
  JALEBI: {
    code: "JALEBI", name: "Jalebi", aliases: ["jalebi", "jalebee"],
    cuisine: "Indian", category: "Dessert", isVeg: true,
    calories: 350, protein: 2, carbs: 58, fat: 12, fiber: 0, sugar: 45, sodium: 100,
    defaultServingG: 60, defaultServingLabel: "3 pieces",
    servingOptions: [{ label: "2 pieces (40g)", grams: 40 }, { label: "3 pieces (60g)", grams: 60 }, { label: "5 pieces (100g)", grams: 100 }],
    tags: ["fried", "sweet", "festive"],
  },
  KHEER: {
    code: "KHEER", name: "Kheer", aliases: ["kheer", "payasam", "rice kheer", "payesh"],
    cuisine: "Indian", category: "Dessert", isVeg: true,
    calories: 155, protein: 4, carbs: 24, fat: 5, fiber: 0.5, sugar: 18, sodium: 60,
    defaultServingG: 150, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (150g)", grams: 150 }, { label: "half bowl (75g)", grams: 75 }],
    tags: ["sweet", "creamy", "festive"],
  },
  HALWA: {
    code: "HALWA", name: "Halwa", aliases: ["halwa", "halva", "sooji halwa", "gajar halwa", "moong dal halwa"],
    cuisine: "Indian", category: "Dessert", isVeg: true,
    calories: 300, protein: 3, carbs: 40, fat: 15, fiber: 1, sugar: 28, sodium: 50,
    defaultServingG: 100, defaultServingLabel: "1 serving",
    servingOptions: [{ label: "small (60g)", grams: 60 }, { label: "1 serving (100g)", grams: 100 }, { label: "large (150g)", grams: 150 }],
    tags: ["sweet", "rich", "festive"],
  },
  LADDU: {
    code: "LADDU", name: "Laddu", aliases: ["laddu", "ladoo", "laddoo", "besan laddu", "motichoor laddu", "boondi laddu"],
    cuisine: "Indian", category: "Dessert", isVeg: true,
    calories: 380, protein: 6, carbs: 45, fat: 20, fiber: 2, sugar: 30, sodium: 40,
    defaultServingG: 50, defaultServingLabel: "1 laddu",
    servingOptions: [{ label: "1 laddu (50g)", grams: 50 }, { label: "2 laddu (100g)", grams: 100 }],
    tags: ["sweet", "festive"],
  },
  BARFI: {
    code: "BARFI", name: "Barfi", aliases: ["barfi", "burfi", "kaju barfi", "kaju katli", "cashew barfi"],
    cuisine: "Indian", category: "Dessert", isVeg: true,
    calories: 390, protein: 7, carbs: 48, fat: 20, fiber: 1, sugar: 35, sodium: 30,
    defaultServingG: 40, defaultServingLabel: "2 pieces",
    servingOptions: [{ label: "1 piece (20g)", grams: 20 }, { label: "2 pieces (40g)", grams: 40 }, { label: "4 pieces (80g)", grams: 80 }],
    tags: ["sweet", "festive", "cashew"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: MORE BEVERAGES
  // ═══════════════════════════════════════
  GREEN_TEA: {
    code: "GREEN_TEA", name: "Green Tea", aliases: ["green tea", "matcha tea"],
    cuisine: "Global", category: "Beverage", isVeg: true,
    calories: 2, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 1,
    defaultServingG: 240, defaultServingLabel: "1 cup",
    servingOptions: [{ label: "1 cup (240ml)", grams: 240 }],
    tags: ["healthy", "antioxidant", "zero-cal"],
  },
  MASALA_CHAI: {
    code: "MASALA_CHAI", name: "Masala Chai", aliases: ["masala chai", "masala tea", "chai tea", "spiced tea"],
    cuisine: "Indian", category: "Beverage", isVeg: true,
    calories: 70, protein: 2, carbs: 10, fat: 2, fiber: 0, sugar: 8, sodium: 30,
    defaultServingG: 150, defaultServingLabel: "1 cup",
    servingOptions: [{ label: "1 cup (150ml)", grams: 150 }, { label: "cutting (75ml)", grams: 75 }, { label: "large (200ml)", grams: 200 }],
    tags: ["hot", "spiced", "classic"],
  },
  LEMON_WATER: {
    code: "LEMON_WATER", name: "Lemon Water", aliases: ["lemon water", "nimbu pani", "nimboo paani", "lime water"],
    cuisine: "Indian", category: "Beverage", isVeg: true,
    calories: 20, protein: 0, carbs: 5, fat: 0, fiber: 0, sugar: 4, sodium: 200,
    defaultServingG: 250, defaultServingLabel: "1 glass",
    servingOptions: [{ label: "1 glass (250ml)", grams: 250 }],
    tags: ["refreshing", "low-cal", "hydrating"],
  },
  COCONUT_WATER: {
    code: "COCONUT_WATER", name: "Coconut Water", aliases: ["coconut water", "nariyal pani", "tender coconut"],
    cuisine: "Indian", category: "Beverage", isVeg: true,
    calories: 19, protein: 0.7, carbs: 4, fat: 0.2, fiber: 0, sugar: 3, sodium: 105,
    defaultServingG: 300, defaultServingLabel: "1 coconut",
    servingOptions: [{ label: "1 glass (250ml)", grams: 250 }, { label: "1 coconut (300ml)", grams: 300 }],
    tags: ["hydrating", "natural", "electrolytes"],
  },
  SUGARCANE_JUICE: {
    code: "SUGARCANE_JUICE", name: "Sugarcane Juice", aliases: ["sugarcane juice", "ganne ka ras"],
    cuisine: "Indian", category: "Beverage", isVeg: true,
    calories: 73, protein: 0.5, carbs: 18, fat: 0, fiber: 0, sugar: 16, sodium: 15,
    defaultServingG: 250, defaultServingLabel: "1 glass",
    servingOptions: [{ label: "1 glass (250ml)", grams: 250 }, { label: "small (150ml)", grams: 150 }],
    tags: ["sweet", "natural", "street-food"],
  },
  MANGO_LASSI: {
    code: "MANGO_LASSI", name: "Mango Lassi", aliases: ["mango lassi", "aam lassi"],
    cuisine: "Indian", category: "Beverage", isVeg: true,
    calories: 120, protein: 3.5, carbs: 22, fat: 2.5, fiber: 0.5, sugar: 18, sodium: 50,
    defaultServingG: 250, defaultServingLabel: "1 glass",
    servingOptions: [{ label: "1 glass (250ml)", grams: 250 }, { label: "small (150ml)", grams: 150 }],
    tags: ["sweet", "refreshing", "yogurt"],
  },
  BADAM_MILK: {
    code: "BADAM_MILK", name: "Badam Milk", aliases: ["badam milk", "almond milk", "badam doodh", "kesar badam"],
    cuisine: "Indian", category: "Beverage", isVeg: true,
    calories: 95, protein: 4, carbs: 12, fat: 4, fiber: 0.5, sugar: 10, sodium: 60,
    defaultServingG: 250, defaultServingLabel: "1 glass",
    servingOptions: [{ label: "1 glass (250ml)", grams: 250 }, { label: "small (150ml)", grams: 150 }],
    tags: ["nutritious", "warm", "festive"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: HEALTHY / GYM / FITNESS
  // ═══════════════════════════════════════
  PROTEIN_SHAKE: {
    code: "PROTEIN_SHAKE", name: "Protein Shake", aliases: ["protein shake", "whey protein", "protein powder", "shake"],
    cuisine: "Global", category: "Supplement", isVeg: true,
    calories: 120, protein: 25, carbs: 3, fat: 1.5, fiber: 0, sugar: 2, sodium: 150,
    defaultServingG: 40, defaultServingLabel: "1 scoop",
    servingOptions: [{ label: "1 scoop (30g)", grams: 30 }, { label: "1.5 scoop (40g)", grams: 40 }, { label: "2 scoops (60g)", grams: 60 }],
    tags: ["high-protein", "gym", "supplement"],
  },
  GREEK_YOGURT: {
    code: "GREEK_YOGURT", name: "Greek Yogurt", aliases: ["greek yogurt", "greek curd", "high protein yogurt"],
    cuisine: "Global", category: "Dairy", isVeg: true,
    calories: 59, protein: 10, carbs: 3.6, fat: 0.7, fiber: 0, sugar: 3, sodium: 36,
    defaultServingG: 200, defaultServingLabel: "1 cup",
    servingOptions: [{ label: "1 cup (200g)", grams: 200 }, { label: "half cup (100g)", grams: 100 }],
    tags: ["high-protein", "low-fat", "probiotic"],
  },
  BOILED_EGGS: {
    code: "BOILED_EGGS", name: "Boiled Egg", aliases: ["boiled egg", "boiled eggs", "hard boiled egg", "egg boiled"],
    cuisine: "Global", category: "Protein", isVeg: false,
    calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, sugar: 1, sodium: 124,
    defaultServingG: 50, defaultServingLabel: "1 egg",
    servingOptions: [{ label: "1 egg (50g)", grams: 50 }, { label: "2 eggs (100g)", grams: 100 }, { label: "3 eggs (150g)", grams: 150 }],
    tags: ["high-protein", "healthy", "gym"],
  },
  BANANA: {
    code: "BANANA", name: "Banana", aliases: ["banana", "kela", "bananas"],
    cuisine: "Global", category: "Fruit", isVeg: true,
    calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sugar: 12, sodium: 1,
    defaultServingG: 120, defaultServingLabel: "1 banana",
    servingOptions: [{ label: "1 small (90g)", grams: 90 }, { label: "1 medium (120g)", grams: 120 }, { label: "1 large (150g)", grams: 150 }],
    tags: ["fruit", "energy", "potassium"],
  },
  APPLE: {
    code: "APPLE", name: "Apple", aliases: ["apple", "seb", "apples"],
    cuisine: "Global", category: "Fruit", isVeg: true,
    calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, sugar: 10, sodium: 1,
    defaultServingG: 180, defaultServingLabel: "1 apple",
    servingOptions: [{ label: "1 small (150g)", grams: 150 }, { label: "1 medium (180g)", grams: 180 }, { label: "1 large (220g)", grams: 220 }],
    tags: ["fruit", "fiber-rich", "healthy"],
  },
  MANGO: {
    code: "MANGO", name: "Mango", aliases: ["mango", "aam", "mangoes"],
    cuisine: "Indian", category: "Fruit", isVeg: true,
    calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, sugar: 14, sodium: 1,
    defaultServingG: 200, defaultServingLabel: "1 cup sliced",
    servingOptions: [{ label: "1 small mango (150g)", grams: 150 }, { label: "1 cup sliced (200g)", grams: 200 }, { label: "1 large mango (300g)", grams: 300 }],
    tags: ["fruit", "sweet", "seasonal"],
  },
  PEANUT_BUTTER: {
    code: "PEANUT_BUTTER", name: "Peanut Butter", aliases: ["peanut butter", "pb"],
    cuisine: "Global", category: "Spread", isVeg: true,
    calories: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, sugar: 9, sodium: 460,
    defaultServingG: 32, defaultServingLabel: "2 tbsp",
    servingOptions: [{ label: "1 tbsp (16g)", grams: 16 }, { label: "2 tbsp (32g)", grams: 32 }],
    tags: ["high-protein", "healthy-fat", "gym"],
  },
  PANEER: {
    code: "PANEER", name: "Paneer", aliases: ["paneer", "cottage cheese", "Indian cheese"],
    cuisine: "Indian", category: "Dairy", isVeg: true,
    calories: 265, protein: 18, carbs: 3, fat: 21, fiber: 0, sugar: 1, sodium: 20,
    defaultServingG: 100, defaultServingLabel: "100g block",
    servingOptions: [{ label: "50g", grams: 50 }, { label: "100g", grams: 100 }, { label: "150g", grams: 150 }],
    tags: ["high-protein", "vegetarian-protein"],
  },
  CHICKEN_BREAST: {
    code: "CHICKEN_BREAST", name: "Chicken Breast", aliases: ["chicken breast", "grilled chicken breast"],
    cuisine: "Global", category: "Protein", isVeg: false,
    calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, sodium: 74,
    defaultServingG: 150, defaultServingLabel: "1 piece",
    servingOptions: [{ label: "1 piece (150g)", grams: 150 }, { label: "200g", grams: 200 }],
    tags: ["high-protein", "low-fat", "gym"],
  },
  SPROUTS: {
    code: "SPROUTS", name: "Sprouts", aliases: ["sprouts", "moong sprouts", "bean sprouts", "ankurit"],
    cuisine: "Indian", category: "Healthy", isVeg: true,
    calories: 30, protein: 3, carbs: 4, fat: 0.2, fiber: 1.8, sugar: 1, sodium: 10,
    defaultServingG: 100, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (100g)", grams: 100 }, { label: "half bowl (50g)", grams: 50 }],
    tags: ["healthy", "protein-rich", "low-cal"],
  },
  POHA: {
    code: "POHA", name: "Poha", aliases: ["poha", "flattened rice", "atuklu", "chivda"],
    cuisine: "Indian", category: "Breakfast", isVeg: true,
    calories: 160, protein: 3, carbs: 28, fat: 4.5, fiber: 1.5, sugar: 2, sodium: 300,
    defaultServingG: 200, defaultServingLabel: "1 plate",
    servingOptions: [{ label: "1 bowl (150g)", grams: 150 }, { label: "1 plate (200g)", grams: 200 }],
    tags: ["light", "breakfast", "maharashtrian"],
  },
  UPMA_RAVA: {
    code: "UPMA_RAVA", name: "Rava Upma", aliases: ["rava upma", "sooji upma"],
    cuisine: "South Indian", category: "Breakfast", isVeg: true,
    calories: 155, protein: 4, carbs: 24, fat: 5, fiber: 1.5, sugar: 1, sodium: 320,
    defaultServingG: 200, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (200g)", grams: 200 }, { label: "half bowl (100g)", grams: 100 }],
    tags: ["breakfast", "semolina"],
  },
  DAHI_VADA: {
    code: "DAHI_VADA", name: "Dahi Vada", aliases: ["dahi vada", "dahi bhalla", "curd vada"],
    cuisine: "North Indian", category: "Snack", isVeg: true,
    calories: 175, protein: 6, carbs: 22, fat: 7, fiber: 2, sugar: 5, sodium: 350,
    defaultServingG: 120, defaultServingLabel: "2 pieces",
    servingOptions: [{ label: "1 piece (60g)", grams: 60 }, { label: "2 pieces (120g)", grams: 120 }, { label: "3 pieces (180g)", grams: 180 }],
    tags: ["cold", "yogurt", "festive"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: RESTAURANT CHAIN ITEMS
  // ═══════════════════════════════════════
  DOMINOS_MARGHERITA: {
    code: "DOMINOS_MARGHERITA", name: "Margherita Pizza (Medium)", aliases: ["margherita pizza", "dominos margherita", "cheese pizza"],
    cuisine: "Fast Food", category: "Pizza", isVeg: true,
    calories: 240, protein: 10, carbs: 30, fat: 9, fiber: 2, sugar: 3, sodium: 560,
    defaultServingG: 100, defaultServingLabel: "1 slice",
    servingOptions: [{ label: "1 slice (100g)", grams: 100 }, { label: "2 slices (200g)", grams: 200 }, { label: "4 slices (400g)", grams: 400 }],
    tags: ["pizza", "restaurant", "fast-food"],
  },
  MCDONALDS_MCALOO: {
    code: "MCDONALDS_MCALOO", name: "McAloo Tikki Burger", aliases: ["mcaloo tikki", "mcd aloo burger", "mcdonald aloo"],
    cuisine: "Fast Food", category: "Burger", isVeg: true,
    calories: 340, protein: 8, carbs: 44, fat: 14, fiber: 3, sugar: 6, sodium: 620,
    defaultServingG: 150, defaultServingLabel: "1 burger",
    servingOptions: [{ label: "1 burger (150g)", grams: 150 }],
    tags: ["fast-food", "restaurant", "burger"],
  },
  MCDONALDS_CHICKEN: {
    code: "MCDONALDS_CHICKEN", name: "McChicken Burger", aliases: ["mcchicken", "mcd chicken burger", "mcdonald chicken"],
    cuisine: "Fast Food", category: "Burger", isVeg: false,
    calories: 400, protein: 15, carbs: 40, fat: 20, fiber: 2, sugar: 5, sodium: 700,
    defaultServingG: 170, defaultServingLabel: "1 burger",
    servingOptions: [{ label: "1 burger (170g)", grams: 170 }],
    tags: ["fast-food", "restaurant", "burger"],
  },
  SUBWAY_VEG: {
    code: "SUBWAY_VEG", name: "Subway Veggie Sub (6\")", aliases: ["subway veggie", "subway veg sub", "veggie delite"],
    cuisine: "Fast Food", category: "Sandwich", isVeg: true,
    calories: 230, protein: 8, carbs: 38, fat: 3, fiber: 4, sugar: 5, sodium: 380,
    defaultServingG: 170, defaultServingLabel: "6-inch sub",
    servingOptions: [{ label: "6-inch (170g)", grams: 170 }, { label: "footlong (340g)", grams: 340 }],
    tags: ["healthy-fast-food", "restaurant"],
  },
  SUBWAY_CHICKEN: {
    code: "SUBWAY_CHICKEN", name: "Subway Chicken Teriyaki (6\")", aliases: ["subway chicken", "chicken teriyaki sub"],
    cuisine: "Fast Food", category: "Sandwich", isVeg: false,
    calories: 330, protein: 22, carbs: 42, fat: 6, fiber: 4, sugar: 8, sodium: 560,
    defaultServingG: 200, defaultServingLabel: "6-inch sub",
    servingOptions: [{ label: "6-inch (200g)", grams: 200 }, { label: "footlong (400g)", grams: 400 }],
    tags: ["restaurant", "high-protein"],
  },
  KFC_CHICKEN: {
    code: "KFC_CHICKEN", name: "KFC Fried Chicken", aliases: ["kfc chicken", "kfc", "fried chicken bucket"],
    cuisine: "Fast Food", category: "Non-Veg", isVeg: false,
    calories: 320, protein: 18, carbs: 12, fat: 22, fiber: 0.5, sugar: 1, sodium: 680,
    defaultServingG: 120, defaultServingLabel: "2 pieces",
    servingOptions: [{ label: "1 piece (60g)", grams: 60 }, { label: "2 pieces (120g)", grams: 120 }, { label: "4 pieces (240g)", grams: 240 }],
    tags: ["fried", "fast-food", "restaurant"],
  },

  // ═══════════════════════════════════════
  // EXPANDED: MORE GLOBAL
  // ═══════════════════════════════════════
  SUSHI: {
    code: "SUSHI", name: "Sushi", aliases: ["sushi", "sushi roll", "maki roll"],
    cuisine: "Japanese", category: "Main", isVeg: false,
    calories: 150, protein: 6, carbs: 28, fat: 2, fiber: 1, sugar: 4, sodium: 500,
    defaultServingG: 150, defaultServingLabel: "6 pieces",
    servingOptions: [{ label: "4 pieces (100g)", grams: 100 }, { label: "6 pieces (150g)", grams: 150 }, { label: "8 pieces (200g)", grams: 200 }],
    tags: ["japanese", "light", "seafood"],
  },
  RAMEN: {
    code: "RAMEN", name: "Ramen", aliases: ["ramen", "ramen noodles", "japanese noodles"],
    cuisine: "Japanese", category: "Main", isVeg: false,
    calories: 190, protein: 10, carbs: 26, fat: 5, fiber: 1.5, sugar: 2, sodium: 700,
    defaultServingG: 400, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "1 bowl (400g)", grams: 400 }, { label: "small (300g)", grams: 300 }],
    tags: ["japanese", "soup", "noodles"],
  },
  PAD_THAI: {
    code: "PAD_THAI", name: "Pad Thai", aliases: ["pad thai", "thai noodles"],
    cuisine: "Thai", category: "Main", isVeg: false,
    calories: 180, protein: 8, carbs: 24, fat: 6, fiber: 1.5, sugar: 4, sodium: 550,
    defaultServingG: 300, defaultServingLabel: "1 plate",
    servingOptions: [{ label: "1 plate (300g)", grams: 300 }, { label: "half plate (150g)", grams: 150 }],
    tags: ["thai", "noodles", "street-food"],
  },
  HUMMUS: {
    code: "HUMMUS", name: "Hummus", aliases: ["hummus", "hummos", "chickpea dip"],
    cuisine: "Middle Eastern", category: "Dip", isVeg: true,
    calories: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, sugar: 0, sodium: 380,
    defaultServingG: 60, defaultServingLabel: "3 tbsp",
    servingOptions: [{ label: "2 tbsp (40g)", grams: 40 }, { label: "3 tbsp (60g)", grams: 60 }, { label: "1/4 cup (80g)", grams: 80 }],
    tags: ["healthy", "protein-rich", "dip"],
  },
  FALAFEL: {
    code: "FALAFEL", name: "Falafel", aliases: ["falafel", "falafels"],
    cuisine: "Middle Eastern", category: "Snack", isVeg: true,
    calories: 333, protein: 13, carbs: 32, fat: 18, fiber: 5, sugar: 2, sodium: 580,
    defaultServingG: 100, defaultServingLabel: "4 pieces",
    servingOptions: [{ label: "2 pieces (50g)", grams: 50 }, { label: "4 pieces (100g)", grams: 100 }, { label: "6 pieces (150g)", grams: 150 }],
    tags: ["fried", "protein-rich", "middle-eastern"],
  },
  AVOCADO_TOAST: {
    code: "AVOCADO_TOAST", name: "Avocado Toast", aliases: ["avocado toast", "avo toast"],
    cuisine: "Western", category: "Breakfast", isVeg: true,
    calories: 220, protein: 5, carbs: 22, fat: 14, fiber: 5, sugar: 2, sodium: 280,
    defaultServingG: 150, defaultServingLabel: "1 slice",
    servingOptions: [{ label: "1 slice (150g)", grams: 150 }, { label: "2 slices (300g)", grams: 300 }],
    tags: ["healthy", "brunch", "trendy"],
  },
  MAGGI: {
    code: "MAGGI", name: "Maggi Noodles", aliases: ["maggi", "maggi noodles", "instant noodles", "noodles", "2 minute noodles"],
    cuisine: "Indian", category: "Snack", isVeg: true,
    calories: 390, protein: 8, carbs: 52, fat: 16, fiber: 3, sugar: 2, sodium: 900,
    defaultServingG: 70, defaultServingLabel: "1 packet",
    servingOptions: [{ label: "1 packet (70g)", grams: 70 }, { label: "2 packets (140g)", grams: 140 }],
    tags: ["instant", "quick", "comfort-food"],
  },
  BREAD_TOAST: {
    code: "BREAD_TOAST", name: "Bread Toast", aliases: ["toast", "bread toast", "toasted bread", "bread"],
    cuisine: "Global", category: "Breakfast", isVeg: true,
    calories: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, sugar: 5, sodium: 491,
    defaultServingG: 30, defaultServingLabel: "1 slice",
    servingOptions: [{ label: "1 slice (30g)", grams: 30 }, { label: "2 slices (60g)", grams: 60 }, { label: "4 slices (120g)", grams: 120 }],
    tags: ["simple", "breakfast", "basic"],
  },
  BUTTER: {
    code: "BUTTER", name: "Butter", aliases: ["butter", "makhan"],
    cuisine: "Global", category: "Condiment", isVeg: true,
    calories: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, sugar: 0.1, sodium: 11,
    defaultServingG: 10, defaultServingLabel: "1 pat",
    servingOptions: [{ label: "1 pat (5g)", grams: 5 }, { label: "1 tbsp (14g)", grams: 14 }, { label: "2 tbsp (28g)", grams: 28 }],
    tags: ["fat", "condiment"],
  },
  GHEE: {
    code: "GHEE", name: "Ghee", aliases: ["ghee", "clarified butter", "desi ghee"],
    cuisine: "Indian", category: "Condiment", isVeg: true,
    calories: 900, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0,
    defaultServingG: 10, defaultServingLabel: "1 tsp",
    servingOptions: [{ label: "1 tsp (5g)", grams: 5 }, { label: "1 tbsp (14g)", grams: 14 }, { label: "2 tbsp (28g)", grams: 28 }],
    tags: ["fat", "traditional", "ayurvedic"],
  },
  PICKLE: {
    code: "PICKLE", name: "Pickle", aliases: ["pickle", "achar", "mango pickle", "avakaya"],
    cuisine: "Indian", category: "Condiment", isVeg: true,
    calories: 150, protein: 1.5, carbs: 8, fat: 13, fiber: 2, sugar: 2, sodium: 1200,
    defaultServingG: 15, defaultServingLabel: "1 tbsp",
    servingOptions: [{ label: "1 tsp (5g)", grams: 5 }, { label: "1 tbsp (15g)", grams: 15 }, { label: "2 tbsp (30g)", grams: 30 }],
    tags: ["spicy", "fermented", "side"],
  },
  RAITA: {
    code: "RAITA", name: "Raita", aliases: ["raita", "cucumber raita", "boondi raita"],
    cuisine: "Indian", category: "Side", isVeg: true,
    calories: 55, protein: 3, carbs: 5, fat: 2.5, fiber: 0.5, sugar: 4, sodium: 200,
    defaultServingG: 100, defaultServingLabel: "1 bowl",
    servingOptions: [{ label: "small (50g)", grams: 50 }, { label: "1 bowl (100g)", grams: 100 }],
    tags: ["cooling", "yogurt", "side"],
  },
  PAPAD: {
    code: "PAPAD", name: "Papad", aliases: ["papad", "papadum", "appalam"],
    cuisine: "Indian", category: "Side", isVeg: true,
    calories: 360, protein: 18, carbs: 42, fat: 12, fiber: 4, sugar: 1, sodium: 1200,
    defaultServingG: 15, defaultServingLabel: "1 papad",
    servingOptions: [{ label: "1 papad (15g)", grams: 15 }, { label: "2 papad (30g)", grams: 30 }],
    tags: ["crispy", "side"],
  },
  MILK: {
    code: "MILK", name: "Milk", aliases: ["milk", "doodh", "whole milk", "full cream milk"],
    cuisine: "Global", category: "Dairy", isVeg: true,
    calories: 62, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sugar: 5, sodium: 46,
    defaultServingG: 250, defaultServingLabel: "1 glass",
    servingOptions: [{ label: "1 glass (250ml)", grams: 250 }, { label: "half glass (125ml)", grams: 125 }],
    tags: ["dairy", "calcium", "basic"],
  },
  HONEY: {
    code: "HONEY", name: "Honey", aliases: ["honey", "shahad"],
    cuisine: "Global", category: "Condiment", isVeg: true,
    calories: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0, sugar: 82, sodium: 4,
    defaultServingG: 21, defaultServingLabel: "1 tbsp",
    servingOptions: [{ label: "1 tsp (7g)", grams: 7 }, { label: "1 tbsp (21g)", grams: 21 }],
    tags: ["natural", "sweetener"],
  },
  WATERMELON: {
    code: "WATERMELON", name: "Watermelon", aliases: ["watermelon", "tarbuz", "tarbuja"],
    cuisine: "Global", category: "Fruit", isVeg: true,
    calories: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, sugar: 6, sodium: 1,
    defaultServingG: 250, defaultServingLabel: "1 cup diced",
    servingOptions: [{ label: "1 cup (250g)", grams: 250 }, { label: "1 slice (300g)", grams: 300 }],
    tags: ["fruit", "hydrating", "low-cal"],
  },
  PAPAYA: {
    code: "PAPAYA", name: "Papaya", aliases: ["papaya", "papita"],
    cuisine: "Indian", category: "Fruit", isVeg: true,
    calories: 43, protein: 0.5, carbs: 11, fat: 0.3, fiber: 1.7, sugar: 8, sodium: 8,
    defaultServingG: 200, defaultServingLabel: "1 cup",
    servingOptions: [{ label: "1 cup (200g)", grams: 200 }, { label: "half cup (100g)", grams: 100 }],
    tags: ["fruit", "digestive", "tropical"],
  },
  PEANUTS: {
    code: "PEANUTS", name: "Peanuts", aliases: ["peanuts", "groundnuts", "moongfali", "roasted peanuts"],
    cuisine: "Global", category: "Snack", isVeg: true,
    calories: 567, protein: 26, carbs: 16, fat: 49, fiber: 9, sugar: 4, sodium: 18,
    defaultServingG: 30, defaultServingLabel: "1 handful",
    servingOptions: [{ label: "1 handful (30g)", grams: 30 }, { label: "1/4 cup (40g)", grams: 40 }],
    tags: ["nuts", "protein-rich", "snack"],
  },
  CASHEWS: {
    code: "CASHEWS", name: "Cashews", aliases: ["cashews", "kaju", "cashew nuts"],
    cuisine: "Global", category: "Snack", isVeg: true,
    calories: 553, protein: 18, carbs: 30, fat: 44, fiber: 3, sugar: 6, sodium: 12,
    defaultServingG: 28, defaultServingLabel: "10 cashews",
    servingOptions: [{ label: "5 cashews (14g)", grams: 14 }, { label: "10 cashews (28g)", grams: 28 }, { label: "15 cashews (42g)", grams: 42 }],
    tags: ["nuts", "snack"],
  },
  WALNUTS: {
    code: "WALNUTS", name: "Walnuts", aliases: ["walnuts", "akhrot"],
    cuisine: "Global", category: "Snack", isVeg: true,
    calories: 654, protein: 15, carbs: 14, fat: 65, fiber: 7, sugar: 3, sodium: 2,
    defaultServingG: 28, defaultServingLabel: "7 walnuts",
    servingOptions: [{ label: "3 walnuts (14g)", grams: 14 }, { label: "7 walnuts (28g)", grams: 28 }],
    tags: ["nuts", "omega-3", "brain-food"],
  },
  DATES: {
    code: "DATES", name: "Dates", aliases: ["dates", "khajoor", "medjool dates"],
    cuisine: "Global", category: "Snack", isVeg: true,
    calories: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 7, sugar: 63, sodium: 1,
    defaultServingG: 40, defaultServingLabel: "2 dates",
    servingOptions: [{ label: "1 date (20g)", grams: 20 }, { label: "2 dates (40g)", grams: 40 }, { label: "4 dates (80g)", grams: 80 }],
    tags: ["natural-sweetener", "energy", "fiber-rich"],
  },
  RAGI_MUDDE: {
    code: "RAGI_MUDDE", name: "Ragi Mudde", aliases: ["ragi mudde", "ragi ball", "finger millet ball", "ragi"],
    cuisine: "South Indian", category: "Main", isVeg: true,
    calories: 110, protein: 3.5, carbs: 22, fat: 1.5, fiber: 3, sugar: 1, sodium: 80,
    defaultServingG: 120, defaultServingLabel: "1 ball",
    servingOptions: [{ label: "1 ball (120g)", grams: 120 }, { label: "2 balls (240g)", grams: 240 }],
    tags: ["millet", "healthy", "karnataka"],
  },
  JOWAR_ROTI: {
    code: "JOWAR_ROTI", name: "Jowar Roti", aliases: ["jowar roti", "jowar bhakri", "sorghum roti"],
    cuisine: "Indian", category: "Bread", isVeg: true,
    calories: 190, protein: 5, carbs: 38, fat: 2, fiber: 4, sugar: 1, sodium: 200,
    defaultServingG: 60, defaultServingLabel: "1 roti",
    servingOptions: [{ label: "1 roti (60g)", grams: 60 }, { label: "2 rotis (120g)", grams: 120 }],
    tags: ["millet", "healthy", "gluten-free"],
  },
  BAJRA_ROTI: {
    code: "BAJRA_ROTI", name: "Bajra Roti", aliases: ["bajra roti", "pearl millet roti", "bajra bhakri"],
    cuisine: "Indian", category: "Bread", isVeg: true,
    calories: 180, protein: 5, carbs: 34, fat: 3, fiber: 4, sugar: 1, sodium: 180,
    defaultServingG: 60, defaultServingLabel: "1 roti",
    servingOptions: [{ label: "1 roti (60g)", grams: 60 }, { label: "2 rotis (120g)", grams: 120 }],
    tags: ["millet", "healthy", "winter"],
  },
};

// Search function — fuzzy match by name/aliases
export function searchFood(query: string): FoodEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const exact: FoodEntry[] = [];
  const partial: FoodEntry[] = [];

  for (const entry of Object.values(FOOD_DATABASE)) {
    const nameMatch = entry.name.toLowerCase().includes(q);
    const aliasMatch = entry.aliases.some(a => a.toLowerCase().includes(q));
    const codeMatch = entry.code.toLowerCase().includes(q.replace(/\s+/g, "_"));

    if (entry.name.toLowerCase() === q || entry.aliases.some(a => a.toLowerCase() === q)) {
      exact.push(entry);
    } else if (nameMatch || aliasMatch || codeMatch) {
      partial.push(entry);
    }
  }

  return [...exact, ...partial].slice(0, 10);
}

// Get food by code
export function getFoodByCode(code: string): FoodEntry | undefined {
  return FOOD_DATABASE[code];
}

// Get best match for a query string
export function getBestMatch(query: string): FoodEntry | undefined {
  const results = searchFood(query);
  return results[0];
}
